## 넘파이 퀴즈 (2026.09.01)

In [1]:
# import문 추가
import numpy as np


arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
# 배열 구성 데이터 타입
arr.dtype

dtype('int64')

In [3]:
# 배열의 행과 열의 요소 갯수
arr.shape

(3, 4)

In [4]:
# 배열 요소의 전체 갯수
arr.size

12

In [5]:
# 리스트로부터 넘파이 배열 생성
mylist = [[1, 2, 3], [4, 5, 6]]
a1 = np.array(mylist, int)

print(a1)

[[1 2 3]
 [4 5 6]]


In [6]:
# mylist로부터 실수형 넘파이 배열 생성

a2 = np.array(mylist, float)
print(a2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# 3 ~ 8 숫자로 1차원 배열 생성
a3 = np.arange(3, 9)

print(a3)

[3 4 5 6 7 8]


In [8]:
# 2 ~ 15 중 짝수로 1차원 배열 생성
a4 = np.arange(2, 16, 2)

print(a4)

[ 2  4  6  8 10 12 14]


In [10]:
# 0 ~ 9의 수열로  2행, 5열의 2차원 배열 생성
a = np.arange(10).reshape(2, 5)

In [11]:
d = np.arange(10)


# 배열 d의 요소를 거꾸로 출력
d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
d2 = d.reshape(2, -1)

# 1번 행 요소를 모두 50으로 변경
d2[1] = 50

In [13]:
data = np.array([4, 6, 7, 3, 2, 0, 10, 1, 6])


# 2보다 크고 6보다 작은 요소만 추출
data[(data > 2) & (data < 6)]

array([4, 3])

In [14]:
data = np.array([4, 6, 7, 3, 2, 0, 10, 1, 6])

# 3로 나눈 나머지가 0인 요소만 추출
data[data % 3 == 0]

array([6, 3, 0, 6])

In [15]:
# 학생들의 점수가 높은 순서로 이름 출력

name_list = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_list = np.array([67, 95, 84, 98, 88])

name_list[np.argsort(score_list)[::-1]]


array(['Kate', 'Mike', 'Samuel', 'Sarah', 'John'], dtype='<U6')