## 1. 넘파이 사용 준비

In [1]:
# 넘파이 설치
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
# numpy를 import하고 별칭을 np로 설정
import numpy as np
# 버전 확인
np.__version__

'2.5.2'

## 2. 넘파이 배열 (ndarray)의 속성

In [5]:
# 넘파이 배열 생성
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
# 데이터 타입, 배열의 차원, 배열의 행과 열의 요소 갯수, 배열 요소의 전체 갯수, 배열 요소의 총 bytes
arr.dtype, arr.ndim, arr.shape, arr.size, arr.nbytes

(dtype('int64'), 2, (3, 4), 12, 96)

In [7]:
# 전치 행렬
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
# 배열의 요소를 1로 초기화
arr.flat = 1
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
# 넘파이 배열의 주요 데이터 타입
b_arr = np.array([True, False, True])
s_arr = np.array(['yellow', 'red'])
print(b_arr.dtype)
print(s_arr.dtype)

bool
<U6


## 3. 넘파이 배열 생성

In [11]:
# 리스트로부터 넘파이 배열 생성
a1 = np.array([1, 2, 3])
a2 = np.array((1, 2, 3))
mylist2 = [[1, 2, 3], [4, 5, 6]]
a3 = np.array(mylist2)

print(a1)
print(a2)
print(a3)


[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [12]:
# 넘파이 배열 생성 시 데이터 타입 지정
a4 = np.array([1, 2, 3], int)
a5 = np.array([1, 2, 3], float)
print(a4)
print(a5)

[1 2 3]
[1. 2. 3.]


In [13]:
# 데이터가 동일 타입이 아닌 경우, 동일 타입으로 변환
a6 = np.array([1, 4, 5, '8'])
a7 = np.array([1, 4, 5, '8'], int)
print(a6)
print(a7)

['1' '4' '5' '8']
[1 4 5 8]


In [14]:
test_list = np.array([1, 4, 5, 'a'], int)
print(test_list)

ValueError: invalid literal for int() with base 10: 'a'

In [15]:
# 0 ~ 3 숫자로 1차원 배열 생성
a=np.arange(4)
print(a, type(a), a.ndim, a.shape)

[0 1 2 3] <class 'numpy.ndarray'> 1 (4,)


In [16]:
# 2 ~ 5 숫자로 1차원 배열 생성
a = np.arange(2, 6)
print(a)

[2 3 4 5]


In [17]:
# 0 ~ 10 중 짝수로 1차원 배열 생성
a1 = np.arange(0, 11, 2)
a2 = np.arange(stop = 11, step = 2)
print(a1)
print(a2)

[ 0  2  4  6  8 10]
[ 0  2  4  6  8 10]


In [18]:
# 2차원 리스트로부터 생성
arr2_list = [[0, 1, 2], [3, 4, 5]]
arr2 = np.array(arr2_list)
print(arr2, arr2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [19]:
# arange() 함수로 행을 생성하여 2차원 배열 생성
m=np.array([np.arange(3), np.arange(3, 6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [20]:
# 3차원 리스트로부터 생성
m=np.array([[[0, 1, 2], [3, 4, 5]],
           [[0, 1, 2], [3, 4, 5]]])
print(m)
print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


## 4. 데이터형 확인과 변환

In [21]:
mylist = [0, 1, 2, 3, 4, 5]
nda=np.array(mylist)

# nda 변수 데이터형 확인
print(type(mylist), type(nda))

# nda 요소의 데이터형 확인
nda.dtype

<class 'list'> <class 'numpy.ndarray'>


dtype('int64')

In [22]:
nda1 = np.array([0, 1, 2, 3.0, 4, 5])
print(nda1, nda1.dtype)

[0. 1. 2. 3. 4. 5.] float64


In [23]:
nda2 = np.array([0, 1, 2, 3, 4, 5])
print(nda2, nda2.dtype)

[0 1 2 3 4 5] int64


In [29]:
# 데이터형 변환 : astype()
a1 = np.array(['1.2', '2.3', '3.4', '4.5'])
print(a1, a1.dtype)

# 문자열 -> 실수형으로 변환
a2 = a1.astype(float)
print(a2, a2.dtype)

# 실수형 -> 정수형으로 변환
a3 = a2.astype(int)
print(a3, a3.dtype)


# 문자열 -> 정수형으로 변환
a5 = np.array(['1', '2', '3'])
print(a5, a5.dtype)
a4 = a5.astype(int)
print(a4, a4.dtype)

['1.2' '2.3' '3.4' '4.5'] <U3
[1.2 2.3 3.4 4.5] float64
[1 2 3 4] int64
['1' '2' '3'] <U1
[1 2 3] int64


## 5. 배열의 형태 변경

In [32]:
# 배열의 구조 변경하기: reshape 함수
m1 = np.arange(6)
print(m1)
print(m1.shape)

# 1행 6열을 6행 1열로 변경
print(m1.reshape(6,1))

[0 1 2 3 4 5]
(6,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [33]:
# 2행 3열로 변경
print(m1.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [ ]:
# 0 ~ 11의 수열로 2면, 2행, 3열의 3차원 배열 생성
print(np.arange(12).reshape(2, 2, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [36]:
m1 = np.arange(6)
print(m1, m1.shape)

# 행 수는 자동, 2열 생성
print(m1.reshape(-1, 2))

# 행 수는 2행, 열 수는 자동 생성
print(m1.reshape(2, -1))


[0 1 2 3 4 5] (6,)
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [37]:
m1=np.arange(6)
m3=m1.reshape(-1, 2, 3)
print(m3, m3.shape)
m3=m1.reshape(-1, 3, 2) # 면 수 자동, 3행 2열 생성
print(m3,m3.shape)
m3=m1.reshape(2, 3, -1) # 열 수 자동, 2면 3행 생성
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [38]:
a = np.arange(12).reshape(3, 4)
print(a, a.shape)

# 다차원 배열을 1차원 배열로 평탄화 : flatten 함수
print(a.flatten)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
<built-in method flatten of numpy.ndarray object at 0x0000015E33B88630>


In [ ]:
# 배열의 방향 변경하기
a = np.arange(12).reshape(3, 4)
print(a, a.shape)

# 행 순서를 거꾸로 변경

# 열 순서를 거꾸로 변경

# 행과 열 순서를 거꾸로 변경

# 행과 열 발향을 서로 바꾸기 (전치 행렬)


## 6. 배열의 인덱싱

In [39]:
# 1차원 배열의 인덱싱
d = np.arange(1, 10)
print(d, d.shape)
print(d[0], d[1], d[2], d[-1], d[-2])

# index 0의 데이터를 10으로 변경
d[0] = 10
print(d)

[1 2 3 4 5 6 7 8 9] (9,)
1 2 3 9 8
[10  2  3  4  5  6  7  8  9]


In [ ]:
# 2차원 배열의 인덱싱
d2 = np.arange(1, 11).reshape(2, -1)

print(d2[0][0]) # 배열명[행][열] 형태
print(d2[0,0]) # 배열명[행,열] 형태
print(d2[1,1])
print(d2[1,-1])

In [ ]:
# 3차원 배열의 인덱싱
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)

print(d3[0][0][0]) # 배열명[면][행][열] 형태
print(d3[0, 0, 0]) # 배열명[면,행,열] 형태
print(d3[1, 1, 2])
print(d3[-1, -1, -1])


## 7. 배열의 슬라이싱

In [40]:
# 1차원 배열의 슬라이싱
d = np.arange(1, 10)
print(d)
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])

[1 2 3 4 5 6 7 8 9]
[3] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8]
[1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


In [47]:
# 2차원 배열의 슬라이싱
d2 = np.arange(1, 11).reshape(2, -1)
print(d2)

# 0행만 슬라이싱
print(d2[0])
# 0행의 전체 열 슬라이싱
print(d2[0])
# 마지막 열 제외한 전체 행과 열 슬라이싱
print(d2[:,:-1])
# 2행 2열 간격으로 전체 행과 열 슬라이싱
print(d2[::2, ::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4]
 [6 7 8 9]]
[[1 3 5]]


In [48]:
# 슬라이싱된 요소값을 한꺼번에 변경
print(d2[::2,::3])
d2[::2,::3]=30 
print(d2)

[[1 4]]
[[30  2  3 30  5]
 [ 6  7  8  9 10]]


In [50]:
# 0번 행 요소를 모두 50으로 변경
d2[0] = 50
print(d2)

[[50 50 50 50 50]
 [ 6  7  8  9 10]]


In [52]:
# 전체 요소값을 한꺼번에 변경
d2[:,:] = -1
print(d2)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [51]:
# 3차원 배열의 슬라이싱
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[:,:-1,:-1])
print(d3[:,1:,1:])
print(d3[:,:,-1])
print(d3[:,-1,-1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1]]

 [[6 7]]]
[[[ 4  5]]

 [[10 11]]]
[[ 2  5]
 [ 8 11]]
[ 5 11]


## 8. 불 인덱싱 (Boolean Indexing)

In [53]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data[data > 3])

[4 6 7]


In [54]:
print(data > 3)

[ True  True  True False False False]


In [55]:
cond = [False, True, True, False, False, True]
data[cond]

array([6, 7, 0])

In [59]:
print(data)
# 2보다 크고 6보다 작은 요소만 추출
print(data[(data > 2) & (data < 6)])
# 2로 나눈 나머지가 0인 요소만 추출
print(data[data % 2 == 0])

# 평균보다 작은 값만 추출
print(data[data < data.mean()])

[4 6 7 3 2 0]
[4 3]
[4 6 2 0]
[3 2 0]


## 9. Fancy Indexing

In [ ]:
f = np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
print(f[indexes])

In [ ]:
f2 = np.array([[1,4], [9,16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
print(f2[x,y])

## 10. 넘파이 배열의 정렬

In [61]:
# 기본 정렬: sort 함수
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(numbers, numbers.shape)

# 오름차순 정렬
print(np.sort(numbers))

# 내림차순 정렬
print(np.sort(numbers)[::-1])

[2 8 9 7 3 1 4 5 6] (9,)
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [62]:
# 2차원 배열의 정렬
arr2d = np.array([[5, 6, 7, 8],
                [4, 3, 2, 1],
                [10, 9, 12, 11]])
print(arr2d)
print(arr2d.shape)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
(3, 4)


In [64]:
np.sort(arr2d)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [65]:
# 열 방향으로 같은 행의 요소 정렬
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [66]:
# 행 방향으로 같은 열의 요소 정렬
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [67]:
# 인덱스 반환 정렬: argsort 함수
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

[2 8 9 7 3 1 4 5 6] (9,)
[5 0 4 6 7 8 3 1 2]


#### [연습문제] 이름과 성적이 각각의 ndarray로 주어진 경우 이름을 성적 순서로 출력하기

In [68]:
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores= np.array([78, 95, 84, 98, 88])

sorted_index = np.argsort(scores)[::-1]

print('성적 내림차순 정렬 시 scores의 인덱스:', sorted_index)
print('성적 오름차순으로 names의 이름 출력:', names[sorted_index])
print('성적 내림차순으로 출력 : ', scores[sorted_index])

성적 내림차순 정렬 시 scores의 인덱스: [3 1 4 2 0]
성적 오름차순으로 names의 이름 출력: ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
성적 내림차순으로 출력 :  [98 95 88 84 78]


## 11. 넘파이 배열의 연산

In [ ]:
# 밸열과 상수의 사칙연산
a = np.array([[1, 2, 3],[4, 5, 6]])
b = 3
print(a + b)

In [ ]:
# 2차원 배열과 1차원 배열의 연산
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2]) 
print(a + b)

In [ ]:
a = np.array([[0], [10], [20], [30]])
b = np.array([0, 1, 2]) 
print(a + b)

## 12. 넘파이 배열의 주요 함수

In [ ]:
# 같은 배열 내 요소의 합 구하기
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(a.sum())

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# 4보다 큰 원소가 하나라도 있는가?


# 모든 원소가 3보다 큰가?


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])

# 각 열(axis=0)에 5보다 큰 원소가 하나라도 있는가?


# 각 행(axis=1)의 모든 원소가 2 이상인가?


In [ ]:
# 1. 배열에 결측치가 하나라도 포함되어 있는지 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data))) # True

# 2. 두 배열이 완전히 동일한지 확인
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2)) # True (요소별 비교 후 전체 확인)